server:
  port: 9000

spring:
  datasource:
     driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
     username: sa
     password: 1
     url: jdbc:sqlserver://localhost:1433;databaseName=TestLin
#    username: root
#    password: 1234
#    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.testDemo.enity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

